apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-popup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-popup
  template:
    metadata:
      labels:
        app: react-popup
    spec:
      containers:
        - name: react-popup
          image: 192.168.1.10:8443/react-popup # 여기에서 React 프로젝트의 이미지로 변경
          #command: ["sh", "-c", "cd /099 && npm install && npm start"]
          ports:
            - containerPort: 80
